### ISSUE TITLE
有可能拿到是无法在外网访问的IPv6地址

### ISSUE THREAD

**Issue by r3inbowari** [adminpass/aliyun_ddns#1]

**Comment by invenleey** [comment]
#2

**Comment by r3inbowari** [comment]
#2 在没有关闭tempaddr的情况下, 多次覆盖最终拿到的ipv6地址无法在外网访问, 因为是通过临时ipv6进行访问的. 所以无论有没有关闭, 都应该默认取ifconfig中的第一个inet6地址.

**Comment by adminpass** [comment]
非常感谢，已做修改 f039cbf32e64d4e7b8e476c0861c890ee7ecb8a3
